---
- name: Update package list
  yum:
    update_cache: yes
  become: yes

- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: install_nvm_result

- name: Debug nvm status
  debug:
    var: install_nvm_result.stdout_lines

- name: Install NodeJS
  shell: bash -lc "nvm install {{ node_version }}"

- name: Set default NodeJS
  shell: bash -lc "nvm alias default {{ node_version }}"

- name: Rsync to install dir
  synchronize:
    src: "{{ app_dir }}"
    dest: "{{ app_install_dir }}"
    mode: push
    rsync_opts:
      - "--exclude=.git"
      - "--delete-after"
      - "--verbose"

- name: Install modules
  command: npm install

- name: Install PM2 globally
  npm:
    name: pm2
    global: yes
    state: present

- name: Stop PM2
  command: pm2 stop {{ app_name }}
  ignore_errors: yes

- name: Start PM2
  command: pm2 start app.js --name {{ app_name}}
  args:
    chdir: "{{ app_install_dir }}/{{ app_name }}"
