---
- name: Update package list
  apt:
    update_cache: yes

- name: Intall Go dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make

- name: Intall bootstrap Go
  apt:
    name: golang
    state: present

- name: Download Go Archive
  get_url:
    url: "{{ go_download_url }}"
    dest: /tmp

- name: Unarchive Go
  unarchive:
    src: "/tmp/{{ go_version }}.src.tar.gz"
    dest: "/tmp/"
    remote_src: yes
    creates: "/tmp/{{ go_version }}/go"

- name: Compile Go
  command: "./make.bash"
  args:
    chdir: "/tmp/{{ go_version }}/go/src"

- name: Copy to target dir
  copy:
    src: "/tmp/{{ go_version }}/go"
    dest: "{{ go_install_dir }}"
    remote_src: yes

- name: Update PATH environment variable
  lineinfile:
    path: /etc/profile.d/go.sh
    state: present
    create: yes
    line: "export PATH={{ go_install_dir }}/go/bin:$PATH"

- name: Reload PATH environment variable
  shell: source /etc/profile.d/go.sh
  args:
    executable: /bin/bash
