---
- name: Update all packages
  apt:
    update_cache: yes

- name: Intall go dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make

- name: Intall first go
  apt:
    name: golang
    state: present

- name: Download Go source code
  ansible.builtin.get_url:
    url: "{{ go_download_url }}"
    dest: /tmp

- name: Untarred directory
  file:
    path: "/tmp/{{ go_version }}"
    state: directory
    mode: 0755

- name: Extract Go
  ansible.builtin.unarchive:
    src: "/tmp/{{ go_version }}.src.tar.gz"
    dest: "/tmp/{{ go_version }}"
    remote_src: yes
    creates: "/tmp/{{ go_version }}/go"

- name: Build Go
  command: "./make.bash"
  args:
    chdir: "/tmp/{{ go_version }}/go/src"

- name: Copy to install directory
  ansible.builtin.copy:
    src: "/tmp/{{ go_version }}/go"
    dest: "{{ go_install_dir }}"
    remote_src: true

- name: Update PATH environment variable
  lineinfile:
    path: /etc/profile.d/go.sh
    state: present
    create: yes
    line: "export PATH={{ go_install_dir }}/go/bin:$PATH"

- name: Reload shell environment
  shell: source /etc/profile.d/go.sh
  args:
    executable: /bin/bash
